# Generated by Django 5.0.7 on 2024-07-29 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('behavior', models.CharField(choices=[('S', 'Skating'), ('L', 'Lewd'), ('O', 'Offensive')], default='S', max_length=1)),
                ('skater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.skater')),
            ],
        ),
    ]
