# Generated by Django 5.0.7 on 2024-07-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_behavior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='behavior',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='behavior',
            name='date',
            field=models.DateField(verbose_name='Behavior Date'),
        ),
    ]
