# Generated by Django 5.0.7 on 2024-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_trick_alter_behavior_options_alter_behavior_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='skater',
            name='tricks',
            field=models.ManyToManyField(to='main_app.trick'),
        ),
    ]
